name: ETF 52w Distance (09:30 & 15:15 IST)

on:
  schedule:
    # IST (UTC+5:30): 09:30 -> 04:00 UTC, 15:15 -> 09:45 UTC
    - cron: '0 4 * * *'
    - cron: '45 9 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  movers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python movers_52w_distance.py
